(cl:defpackage face_recognition-msg
  (:use )
  (:export
   "<FRCLIENTGOAL>"
   "FRCLIENTGOAL"
   "<FACERECOGNITIONACTIONFEEDBACK>"
   "FACERECOGNITIONACTIONFEEDBACK"
   "<FACERECOGNITIONACTION>"
   "FACERECOGNITIONACTION"
   "<FACERECOGNITIONACTIONRESULT>"
   "FACERECOGNITIONACTIONRESULT"
   "<FACERECOGNITIONFEEDBACK>"
   "FACERECOGNITIONFEEDBACK"
   "<FACERECOGNITIONACTIONGOAL>"
   "FACERECOGNITIONACTIONGOAL"
   "<FACERECOGNITIONRESULT>"
   "FACERECOGNITIONRESULT"
   "<FACERECOGNITIONGOAL>"
   "FACERECOGNITIONGOAL"
  ))

